     </article>
   </div>
 </section>
 <footer id="page-footer">
  <div class="container">
 <div class="footer-logo">
        <img class="png" src="assets/footer_logo.png" alt="Ubuntu" /><br /><br /><img class="png" src="assets/canonical_footer_logo.png" alt="Canonical" />
</div>
   <div class="copyright">
    <p>&copy; 2011 Canonical Ltd., Ubuntu Community. Ubuntu and Canonical are registered trademarks of Canonical Ltd.
<br />
<br />
Problems with this site? <a href="https://bugs.launchpad.net/unify/+filebug">File a Bug</a></p>
   </div>
  </div>
 </footer>
</body>

</html>

