
<!DOCTYPE HTML> 
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Design bugs for Ubuntu</title>

  <link rel="stylesheet" type="text/css" href="assets/status.css" />
  <link rel="stylesheet" type="text/css" href="assets/theme.css" />

  <script type="text/javascript" src="assets/sortable.js"></script>
  <script type="text/javascript" src="assets/collapsable.js"></script>
</head>




<body id="home">
        <aside id="top-nav">
            <div class="container">
               <section id="top-login"> 
               </section> 
                <nav id="top-related">
                    <a class="top-nav-item" href="http://www.ubuntu.com">Ubuntu.com</a>
                    <a class="top-nav-item" href="http://people.canonical.com/~platform/desktop/versions.html">Desktop updates</a>
                    <a class="top-nav-item" href="http://pad.ubuntu.com/ubuntu-desktop">Desktop Etherpad</a>
                </nav>
            </div>
        </aside>

 <header id="page-header">
  <div class="container" >
   <nav id="main-nav">
    <a class="main-nav-item" href="designer.html">Design</a>
    <a class="main-nav-item" href="upstream.html">Upstream</a>
    <a class="main-nav-item" href="downstream.html">Downstream</a>
    <a class="main-nav-item" href="stats.html">Statistics</a>
   </nav>

   <h1 id="top-logo"><img class="png" id="the-logo" src="http://www.ubuntu.com/sites/default/themes/ubuntu10/logo.png" alt="Ubuntu" width="118" height="27" /><span id="loco">Designify Tracker</span></h1>

  </div>
 </header>

 <section id="main-section">
  <div class="container" >
   <article class="main-content">
